create extension if not exists pgcrypto;

-- Single-user hackathon posture: Supabase Auth and RLS are intentionally
-- deferred. Do not add user_id/auth.uid() policies until the product moves
-- beyond the single-user demo scope documented in AGENTS.md.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.business_profiles (
  id text primary key default gen_random_uuid()::text,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.attributes (
  id bigint generated by default as identity primary key,
  business_profile_id text not null references public.business_profiles(id) on delete cascade,
  key text not null,
  label text not null,
  value text not null,
  sensitivity text not null default 'business',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attributes_sensitivity_check
    check (sensitivity in ('public', 'business', 'personal', 'confidential')),
  constraint attributes_profile_key_unique unique (business_profile_id, key)
);

create table if not exists public.documents (
  id text primary key default gen_random_uuid()::text,
  business_profile_id text not null references public.business_profiles(id) on delete cascade,
  filename text not null,
  mime text not null,
  blob_ref text,
  created_at timestamptz not null default now()
);

create table if not exists public.extracted_facts (
  id text primary key default gen_random_uuid()::text,
  business_profile_id text references public.business_profiles(id) on delete cascade,
  document_id text references public.documents(id) on delete set null,
  source text,
  key text not null,
  value text not null,
  evidence_note text,
  confidence numeric(4, 3) not null default 0,
  sensitivity text not null default 'business',
  expiry_marker text,
  created_at timestamptz not null default now(),
  constraint extracted_facts_confidence_check check (confidence >= 0 and confidence <= 1),
  constraint extracted_facts_sensitivity_check
    check (sensitivity in ('public', 'business', 'personal', 'confidential'))
);

create table if not exists public.form_definitions (
  id text primary key default gen_random_uuid()::text,
  jurisdiction text not null,
  agency text not null,
  name text not null,
  portal_url text,
  prerequisites jsonb not null default '[]'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.form_fields (
  id bigint generated by default as identity primary key,
  form_definition_id text not null references public.form_definitions(id) on delete cascade,
  key text not null,
  label text not null,
  section text not null,
  type text not null,
  options jsonb,
  sensitivity text not null default 'business',
  required boolean not null default false,
  human_only boolean not null default false,
  provenance text not null default 'agent_fillable',
  conditional_on text,
  notes text,
  position integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint form_fields_type_check
    check (type in ('text', 'select', 'multi_select', 'radio', 'checkbox', 'date', 'number', 'upload', 'button')),
  constraint form_fields_sensitivity_check
    check (sensitivity in ('public', 'business', 'personal', 'confidential')),
  constraint form_fields_provenance_check
    check (provenance in ('agent_fillable', 'retrieved', 'human_only', 'user_supplied')),
  constraint form_fields_definition_key_unique unique (form_definition_id, key)
);

create table if not exists public.filing_tasks (
  id text primary key default gen_random_uuid()::text,
  business_profile_id text not null references public.business_profiles(id) on delete cascade,
  form_definition_id text references public.form_definitions(id) on delete set null,
  status text not null default 'not_started',
  origin text not null default 'manual',
  blocker jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint filing_tasks_status_check
    check (status in ('not_started', 'in_progress', 'action_required', 'completed')),
  constraint filing_tasks_origin_check
    check (origin in ('auto_suggested', 'manual'))
);

create table if not exists public.recommendations (
  id text primary key default gen_random_uuid()::text,
  task_id text not null references public.filing_tasks(id) on delete cascade,
  reason text not null default '',
  prerequisites jsonb not null default '[]'::jsonb,
  fee text,
  timeline text,
  warnings jsonb not null default '[]'::jsonb,
  source_links jsonb not null default '[]'::jsonb,
  confidence numeric(4, 3) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recommendations_task_unique unique (task_id),
  constraint recommendations_confidence_check check (confidence >= 0 and confidence <= 1)
);

create table if not exists public.field_records (
  id text primary key default gen_random_uuid()::text,
  task_id text not null references public.filing_tasks(id) on delete cascade,
  field_key text not null,
  label text not null,
  section text not null,
  proposed_value text,
  sources jsonb not null default '[]'::jsonb,
  confidence numeric(4, 3) not null default 0,
  sensitivity text not null default 'business',
  status text not null,
  reason text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint field_records_confidence_check check (confidence >= 0 and confidence <= 1),
  constraint field_records_sensitivity_check
    check (sensitivity in ('public', 'business', 'personal', 'confidential')),
  constraint field_records_status_check
    check (status in ('filled', 'left_blank', 'needs_review', 'blocked', 'user_required', 'not_applicable')),
  constraint field_records_task_field_unique unique (task_id, field_key)
);

create table if not exists public.agent_events (
  id bigint generated by default as identity primary key,
  task_id text not null references public.filing_tasks(id) on delete cascade,
  type text not null,
  payload jsonb not null default '{}'::jsonb,
  timestamp timestamptz not null default now()
);

create index if not exists attributes_profile_idx on public.attributes (business_profile_id);
create index if not exists documents_profile_idx on public.documents (business_profile_id);
create index if not exists extracted_facts_profile_idx on public.extracted_facts (business_profile_id);
create index if not exists extracted_facts_document_idx on public.extracted_facts (document_id);
create index if not exists form_fields_definition_idx on public.form_fields (form_definition_id);
create index if not exists filing_tasks_status_idx on public.filing_tasks (status);
create index if not exists filing_tasks_profile_idx on public.filing_tasks (business_profile_id);
create index if not exists field_records_task_idx on public.field_records (task_id);
create index if not exists agent_events_task_timestamp_idx on public.agent_events (task_id, timestamp);

drop trigger if exists set_business_profiles_updated_at on public.business_profiles;
create trigger set_business_profiles_updated_at
before update on public.business_profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_attributes_updated_at on public.attributes;
create trigger set_attributes_updated_at
before update on public.attributes
for each row execute function public.set_updated_at();

drop trigger if exists set_form_definitions_updated_at on public.form_definitions;
create trigger set_form_definitions_updated_at
before update on public.form_definitions
for each row execute function public.set_updated_at();

drop trigger if exists set_form_fields_updated_at on public.form_fields;
create trigger set_form_fields_updated_at
before update on public.form_fields
for each row execute function public.set_updated_at();

drop trigger if exists set_filing_tasks_updated_at on public.filing_tasks;
create trigger set_filing_tasks_updated_at
before update on public.filing_tasks
for each row execute function public.set_updated_at();

drop trigger if exists set_recommendations_updated_at on public.recommendations;
create trigger set_recommendations_updated_at
before update on public.recommendations
for each row execute function public.set_updated_at();

drop trigger if exists set_field_records_updated_at on public.field_records;
create trigger set_field_records_updated_at
before update on public.field_records
for each row execute function public.set_updated_at();
